DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS summary;
DROP TABLE IF EXISTS taxes;
 
CREATE TABLE orders (
	id integer NOT NULL,
	stock varchar(10) NOT NULL,
	date date NOT NULL,
	count integer NOT NULL,
	price number NOT NULL,
	ordertype varchar(1) NOT NULL
);
ALTER TABLE orders ADD CONSTRAINT pk_orders PRIMARY KEY (id);

CREATE TABLE summaries (
	id integer NOT NULL,
	stock varchar(10) NOT NULL,
	date date NOT NULL,
	count integer NOT NULL,
	avgprice number NOT NULL,
	daytrade boolean NOT NULL
);
ALTER TABLE summaries ADD CONSTRAINT pk_summaries PRIMARY KEY (id);

CREATE TABLE taxes (
	id integer NOT NULL,
	stock varchar(10) NOT NULL,
	date date NOT NULL,
	dueprice number NOT NULL
);
ALTER TABLE taxes ADD CONSTRAINT pk_taxes PRIMARY KEY (id);

CREATE TABLE stocks (
	id integer NOT NULL,
	stock varchar(10) NOT NULL,
	price number NOT NULL,
	updated date NOT NULL
);

CREATE SEQUENCE seq_orders;
CREATE SEQUENCE seq_summary;
CREATE SEQUENCE seq_taxes;
CREATE SEQUENCE seq_stocks;

CREATE TABLE scheduler_job_info (
	id bigint generated by default as identity,
	cron_expression varchar(255),
	cron_job boolean,
	job_class varchar(255),
	job_group varchar(255),
	job_name varchar(255),
	repeat_time bigint,
	primary key (id)
);